apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["sleep","3600"]
    volumeMounts:
    - mountPath: /mnt/test-vol
      name: test-vol
  volumes:
  - name: test-vol
    persistentVolumeClaim:
      claimName: test-pvc
