apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim3
spec:
  storageClassName: acs-abs
  dataSource:
    name: claim1
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

